# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='interest',
            field=models.CharField(default='gernal', max_length=255),
            preserve_default=False,
        ),
    ]
