# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postmodel_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='interest',
        ),
    ]
