# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_postmodel_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash2Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='hash2post',
            name='id_of_hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.HashTag'),
        ),
        migrations.AddField(
            model_name='hash2post',
            name='id_of_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.PostModel'),
        ),
    ]
